name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe the feature as a user story
      placeholder: |
        As a [type of user],
        I want [some goal or objective],
        So that [some reason or benefit].
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature
      placeholder: Describe what you'd like to see implemented
    validations:
      required: true

  - type: textarea
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: What criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Feature works as described
        - [ ] Tests are written and passing
        - [ ] Documentation is updated
        - [ ] Code is reviewed and merged
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features?
      placeholder: Describe any alternative approaches you've thought about
    validations:
      required: false

  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues
      description: Are there any related or blocking issues?
      placeholder: |
        Related to: #123
        Blocks: #456
        Blocked by: #789
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature
    validations:
      required: false
